name: Premier pipeline avec git hub action
on: push
jobs:
  run-shell-command:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello ${{ matrix.os }}"